# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f6cee78285d4f7cd2421fde3efc4fad26414c56c805b03da5e63d4d7331c4a8e56da872b668b91a3d218987ca6bea16fc46ca004ec3c03e18c5e1ceb66c08a

test:
  secret_key_base: 5042298ec9ca7eda74faba6dccddd57906e2831a885478bf7bc071853492993359f8b00650de81803d5599662b48ac8e57ab09f281a9db72e24ce3dbe279f3df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
